=== m4rocks/paquet/app-spec-schema.json
{"$ref":"#/definitions/appSpec","definitions":{"appSpec":{"type":"object","properties":{"$schema":{"type":"string"},"id":{"type":"string","minLength":1,"maxLength":50,"pattern":"^[a-z0-9](?:[a-z0-9.-]*[a-z0-9])?$"},"url":{"type":"string","format":"uri"},"manifestUrl":{"type":"string","format":"uri"},"features":{"type":"array","items":{"type":"string","enum":["openSource","mobile","desktop","auth","offline"]}},"githubUrl":{"type":"string","format":"uri","pattern":"^https\\:\\/\\/github\\.com\\/"},"gitlabUrl":{"type":"string","format":"uri","pattern":"^https\\:\\/\\/gitlab\\.com\\/"},"categories":{"type":"array","items":{"type":"string","enum":["news","social","chat","messenger","messaging","entertainment","video","movies","tv","streaming","utilities","tool","tools","utility","productivity","work","business","office","education","games","game","gaming","music","audio","sound","development","code","coding","program","programming","developer","developers","lifestyle","photo","travel","trip","health","books"]}},"author":{"type":"string","minLength":1,"maxLength":30},"authorUrl":{"type":"string","format":"uri"},"accentColor":{"type":"string"},"updatedDate":{"type":"string","format":"date"}},"required":["$schema","id","url","features","author","updatedDate"],"additionalProperties":false}},"$schema":"http://json-schema.org/draft-07/schema#"}

=== m4rocks/paquet/apps/io.github.maxmoffa.mydiary.public.json
{
	"$schema": "../app-spec-schema.json",
	"id": "io.github.maxmoffa.mydiary.public",
	"url": "https://maxmoffa.github.io/mydiary/public",
	"manifestUrl": "https://maxmoffa.github.io/mydiary/public/manifest.json",
	"features": [
		"openSource",
		"mobile",
		"offline",
		"desktop"
	],
	"githubUrl": "https://github.com/MaxMoffa/MyDiary",
	"categories": [
		"productivity",
		"utilities"
	],
	"author": "Massimo Moffa",
	"accentColor": "#d0c589",
	"updatedDate": "2025-04-08"
}

=== m4rocks/paquet/apps/io.github.hexacolonist.json
{
	"$schema": "../app-spec-schema.json",
	"id": "io.github.hexacolonist",
	"url": "https://hexacolonist.github.io",
	"manifestUrl": "https://hexacolonist.github.io/manifest.webmanifest",
	"features": [
		"mobile",
		"desktop",
		"openSource",
		"offline"
	],
	"categories": ["games"],
	"githubUrl": "https://github.com/hexacolonist/hexacolonist.github.io",
	"author": "ShuP1",
	"updatedDate": "2025-04-15"
}

=== m4rocks/paquet/apps/com.google.travel.json
{
	"$schema": "../app-spec-schema.json",
	"id": "com.google.travel",
	"url": "https://www.google.com/travel",
	"manifestUrl": "https://www.google.com/_/TravelFrontendUi/manifest.json",
	"features": [
		"mobile",
		"desktop"
	],
	"categories": [
		"lifestyle"
	],
	"author": "Google",
	"accentColor": "#fabc05",
	"updatedDate": "2025-04-08"
}

=== m4rocks/paquet/apps/site.esstudio.newsfeeder.json
{
	"$schema": "../app-spec-schema.json",
	"id": "site.esstudio.newsfeeder",
	"url": "https://newsfeeder.esstudio.site",
	"manifestUrl": "https://newsfeeder.esstudio.site/manifest.json",
	"features": [
		"mobile",
		"desktop"
	],
	"categories": [
		"news"
	],
	"author": "Sem Postma",
	"accentColor": "#f45c3d",
	"updatedDate": "2025-04-08"
}

=== m4rocks/paquet/apps/com.recipesage.json
{
	"$schema": "../app-spec-schema.json",
	"id": "com.recipesage",
	"url": "https://recipesage.com",
	"author": "Julian Poyourow",
	"manifestUrl": "https://recipesage.com/manifest.json",
	"features": [
		"openSource",
		"mobile",
        "desktop",
		"offline",
        "auth"
	],
	"categories": ["productivity"],
	"githubUrl": "https://github.com/julianpoy/RecipeSage",
	"updatedDate": "2025-04-08"
}

=== m4rocks/paquet/apps/eu.mconverter.json
{
	"$schema": "../app-spec-schema.json",
	"id": "eu.mconverter",
	"url": "https://mconverter.eu",
	"manifestUrl": "https://mconverter.eu/manifest.json",
	"features": [
		"mobile",
		"desktop"
	],
	"categories": [
		"utilities",
		"lifestyle",
		"entertainment"
	],
	"author": "MConverter",
	"accentColor": "#5494fc",
	"updatedDate": "2025-04-15"
}

=== m4rocks/paquet/apps/com.instagram.json
{
	"$schema": "../app-spec-schema.json",
	"id": "com.instagram",
	"url": "https://www.instagram.com",
	"manifestUrl": "https://www.instagram.com/data/manifest.json/",
	"features": [
		"mobile",
		"desktop",
		"auth"
	],
	"categories": [
		"social"
	],
	"author": "Meta",
	"accentColor": "#c43c7c",
	"updatedDate": "2025-04-08"
}

=== m4rocks/paquet/apps/com.youtube.music.json
{
	"$schema": "../app-spec-schema.json",
	"id": "com.youtube.music",
	"url": "https://music.youtube.com/",
	"manifestUrl": "https://music.youtube.com/manifest.webmanifest",
	"features": [
		"mobile",
		"desktop"
	],
	"categories": [
		"entertainment",
		"music"
	],
	"author": "YouTube",
	"accentColor": "#fc0404",
	"updatedDate": "2025-04-08"
}
