=== m4rocks/paquet/app-spec-schema.json
{"$ref":"#/definitions/appSpec","definitions":{"appSpec":{"type":"object","properties":{"$schema":{"type":"string"},"id":{"type":"string","minLength":1,"maxLength":50,"pattern":"^[a-z0-9](?:[a-z0-9.-]*[a-z0-9])?$"},"url":{"type":"string","format":"uri"},"manifestUrl":{"type":"string","format":"uri"},"features":{"type":"array","items":{"type":"string","enum":["openSource","mobile","desktop","auth","offline"]}},"githubUrl":{"type":"string","format":"uri","pattern":"^https\\:\\/\\/github\\.com\\/"},"gitlabUrl":{"type":"string","format":"uri","pattern":"^https\\:\\/\\/gitlab\\.com\\/"},"categories":{"type":"array","items":{"type":"string","enum":["news","social","chat","messenger","messaging","entertainment","video","movies","tv","streaming","utilities","tool","tools","utility","productivity","work","business","office","education","games","game","gaming","music","audio","sound","development","code","coding","program","programming","developer","developers","lifestyle","photo","travel","trip","health","books"]}},"author":{"type":"string","minLength":1,"maxLength":30},"authorUrl":{"type":"string","format":"uri"},"accentColor":{"type":"string"},"updatedDate":{"type":"string","format":"date"}},"required":["$schema","id","url","features","author","updatedDate"],"additionalProperties":false}},"$schema":"http://json-schema.org/draft-07/schema#"}

=== m4rocks/paquet/apps/com.firebaseapp.beat-tap.json
{
	"$schema": "../app-spec-schema.json",
	"id": "com.firebaseapp.beat-tap",
	"url": "https://beat-tap.firebaseapp.com",
	"manifestUrl": "https://beat-tap.firebaseapp.com/manifest.json",
	"features": [
		"mobile",
		"desktop",
		"offline"
	],
	"categories": [
		"music"
	],
	"author": "Unknown",
	"accentColor": "#7ce6ba",
	"updatedDate": "2025-04-16"
}

=== m4rocks/paquet/apps/org.telegram.web.a.json
{
	"$schema": "../app-spec-schema.json",
	"id": "org.telegram.web.a",
	"url": "https://web.telegram.org/a",
	"manifestUrl": "https://web.telegram.org/a/site.webmanifest",
	"features": [
		"mobile",
		"desktop",
		"openSource",
		"offline",
		"auth"
	],
	"githubUrl": "https://github.com/Ajaxy/telegram-tt",
	"categories": [
		"social"
	],
	"author": "Telegram",
	"accentColor": "#2ca4dc",
	"updatedDate": "2025-04-09"
}

=== m4rocks/paquet/apps/com.keyli3e.linef.json
{
	"$schema": "../app-spec-schema.json",
	"id": "com.keyli3e.linef",
	"url": "https://linef.keyli3e.com/",
	"features": [
		"openSource",
		"mobile",
		"desktop",
		"offline"
	],
	"categories": [
		"games"
	],
	"githubUrl": "https://github.com/tnlx/linef",
	"author": "Thuc Le",
	"updatedDate": "2025-04-08"
}
