=== m4rocks/paquet/app-spec-schema.json
{"$ref":"#/definitions/appSpec","definitions":{"appSpec":{"type":"object","properties":{"$schema":{"type":"string"},"id":{"type":"string","minLength":1,"maxLength":50,"pattern":"^[a-z0-9](?:[a-z0-9.-]*[a-z0-9])?$"},"url":{"type":"string","format":"uri"},"manifestUrl":{"type":"string","format":"uri"},"features":{"type":"array","items":{"type":"string","enum":["openSource","mobile","desktop","auth","offline"]}},"githubUrl":{"type":"string","format":"uri","pattern":"^https\\:\\/\\/github\\.com\\/"},"gitlabUrl":{"type":"string","format":"uri","pattern":"^https\\:\\/\\/gitlab\\.com\\/"},"categories":{"type":"array","items":{"type":"string","enum":["news","social","chat","messenger","messaging","entertainment","video","movies","tv","streaming","utilities","tool","tools","utility","productivity","work","business","office","education","games","game","gaming","music","audio","sound","development","code","coding","program","programming","developer","developers","lifestyle","photo","travel","trip","health","books"]}},"author":{"type":"string","minLength":1,"maxLength":30},"authorUrl":{"type":"string","format":"uri"},"accentColor":{"type":"string"},"updatedDate":{"type":"string","format":"date"}},"required":["$schema","id","url","features","author","updatedDate"],"additionalProperties":false}},"$schema":"http://json-schema.org/draft-07/schema#"}

=== m4rocks/paquet/apps/app.vercel.cuzzle-react.json
{
	"$schema": "../app-spec-schema.json",
	"id": "app.vercel.cuzzle-react",
	"url": "https://cuzzle-react.vercel.app",
	"manifestUrl": "https://cuzzle-react.vercel.app/manifest.json",
	"features": [
		"mobile",
		"desktop",
		"openSource"
	],
	"categories": [
		"games"
	],
	"author": "Jorge Rubiano",
	"accentColor": "#c0416a",
	"updatedDate": "2025-04-08"
}

=== m4rocks/paquet/apps/io.github.nenadalm.virus-wars.json
{
	"$schema": "../app-spec-schema.json",
	"id": "io.github.nenadalm.virus-wars",
	"url": "https://nenadalm.github.io/virus-wars/",
	"manifestUrl": "https://nenadalm.github.io/virus-wars/manifest.json",
	"features": [
		"openSource",
		"mobile",
		"offline"
	],
	"categories": ["games"],
	"author": "Miloslav Nenad√°l",
	"githubUrl": "https://github.com/nenadalm/virus-wars",
	"updatedDate": "2025-04-15"
}

=== m4rocks/paquet/apps/sh.surge.beta-lyricfy.json
{
	"$schema": "../app-spec-schema.json",
	"id": "sh.surge.beta-lyricfy",
	"url": "https://beta-lyricfy.surge.sh",
	"manifestUrl": "https://beta-lyricfy.surge.sh/manifest.json",
	"features": [
		"mobile",
		"desktop",
		"auth"
	],
	"categories": [
		"utilities",
		"music"
	],
	"author": "Lyricfy",
	"accentColor": "#54e4b9",
	"updatedDate": "2025-04-15"
}

=== m4rocks/paquet/apps/org.telegram.web.z.json
{
	"$schema": "../app-spec-schema.json",
	"id": "org.telegram.web.z",
	"url": "https://web.telegram.org/z",
	"manifestUrl": "https://web.telegram.org/z/site.webmanifest",
	"features": [
		"mobile",
		"desktop",
		"openSource",
		"offline",
		"auth"
	],
	"githubUrl": "https://github.com/Ajaxy/telegram-tt",
	"categories": [
		"social"
	],
	"author": "Telegram",
	"accentColor": "#2ca4dc",
	"updatedDate": "2025-04-08"
}

=== m4rocks/paquet/apps/com.similarworlds.json
{
	"$schema": "../app-spec-schema.json",
	"id": "com.similarworlds",
	"url": "https://similarworlds.com",
	"manifestUrl": "https://similarworlds.com/manifest.json",
	"features": [
		"mobile",
		"desktop"
	],
	"categories": [
		"social",
		"entertainment",
		"lifestyle",
		"news"
	],
	"author": "Similar Worlds",
	"accentColor": "#ec7c22",
	"updatedDate": "2025-04-08"
}

=== m4rocks/paquet/apps/io.github.svimanet.blockit.json
{
	"$schema": "../app-spec-schema.json",
	"id": "io.github.svimanet.blockit",
	"url": "https://svimanet.github.io/blockit/",
	"author": "Eirik",
	"features": [
		"openSource",
		"mobile",
		"desktop",
		"offline"
	],
	"githubUrl": "https://github.com/svimanet/blockit",
	"categories": [
		"games"
	],
	"updatedDate": "2025-04-15"
}

=== m4rocks/paquet/apps/io.pomofocus.json
{
	"$schema": "../app-spec-schema.json",
	"id": "io.pomofocus",
	"url": "https://pomofocus.io",
	"manifestUrl": "https://pomofocus.io/manifest.json",
	"features": [
		"mobile",
		"desktop"
	],
	"categories": [
		"productivity",
		"utilities"
	],
	"author": "Yuya Uzu",
	"accentColor": "#cc5c5c",
	"updatedDate": "2025-04-08"
}

=== m4rocks/paquet/apps/win.freesolitaire.json
{
	"$schema": "../app-spec-schema.json",
	"id": "win.freesolitaire",
	"url": "https://freesolitaire.win",
	"manifestUrl": "https://freesolitaire.win/manifest.json",
	"features": [
		"mobile",
		"desktop",
		"offline"
	],
	"categories": [
		"games"
	],
	"author": "Unknown",
	"accentColor": "#449444",
	"updatedDate": "2025-04-08"
}
